apiVersion: v1
kind: Secret
metadata:
  name: {{ template "server.fullname" . }}
  labels:
    app: {{ template "server.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
type: Opaque
data:
  secret: {{ .Values.server.secret.secret | b64enc | quote }}
  github-secret: {{ .Values.server.secret.githubSecret | b64enc | quote }}
  db-source: {{ .Values.server.config.dbSource | b64enc | quote }}
