  apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    name: "{{ template "server.fullname" . }}-ws"
    labels:
      chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    annotations:
      nginx.org/websocket-services: ws-svc
  spec:
    rules:
    - host: {{ .Values.server.host }}
      http:
        paths:
        - path: /ws
          backend:
            serviceName: {{ template "server.fullname" . }}
            servicePort: 80
