apiVersion: v1
kind: Service
metadata:
  name: {{ template "server.fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  selector:
    app: {{ template "server.fullname" . }}
  ports:
  - protocol: TCP
    port: {{ .Values.server.externalPort }}
    targetPort: {{ .Values.server.internalPort }}
    name: http
