  apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    name: {{ template "server.fullname" . }}
    labels:
      chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  spec:
    rules:
    - host: {{ .Values.server.host }}
      http:
        paths:
        - backend:
            serviceName: {{ template "server.fullname" . }}
            servicePort: 80
          path: /
