apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "worker.fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.worker.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "worker.fullname" . }}
    spec:
      containers:
      - name: "{{ .Chart.Name }}"
        command:
        - /drone
        - agent
        image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
        imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
        volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
        env:
        - name: DRONE_SERVER
          value: "ws://{{ template "server.fullname" . }}:{{ .Values.server.externalPort }}/ws/broker"
        - name: DRONE_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ template "server.fullname" . }}
              key: secret
        resources:
{{ toYaml .Values.worker.resources | indent 12 }}
      volumes:
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
